In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
#One dimensional array
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
#Two dimensional array
a2=np.array([[1,2.1,3],[4,5,6.4]])
a2

array([[1. , 2.1, 3. ],
       [4. , 5. , 6.4]])

In [4]:
#Three Dimensional array
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Attributes

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(3, 3)

In [8]:
#Check dimensions 
a1.ndim,a2.ndim,a3.ndim

(1, 2, 2)

In [9]:
# Size of an array(NUmber of elements)
a1.size,a2.size,a3.size

(3, 6, 9)

In [10]:
# datatype of an array
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [11]:
#Type of an array
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
# To create dataframe using pandas
import pandas as pd

In [13]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
df=pd.DataFrame(a3)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Arrays 

In [15]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
# fill array with ones
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# Fill with zeros
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Type of both arrays
type(ones),type(zeros)

(numpy.ndarray, numpy.ndarray)

In [19]:
# Array with range(Start,stop,step)
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
# Random integer
random_array1=np.random.randint(0,10,size=(3,5))
random_array1

array([[8, 2, 0, 4, 4],
       [4, 7, 6, 8, 8],
       [4, 0, 5, 5, 4]])

In [21]:
random_array2=np.random.random((5,3))
random_array2

array([[0.45677861, 0.38987068, 0.64307463],
       [0.80967299, 0.42118732, 0.90893246],
       [0.42590102, 0.22667638, 0.51390929],
       [0.00513323, 0.15793045, 0.0724784 ],
       [0.50445664, 0.75992335, 0.80255848]])

In [22]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.70480631, 0.47151994, 0.6359812 ],
       [0.80096643, 0.42151329, 0.21534192],
       [0.12647601, 0.46041436, 0.14726363],
       [0.65629194, 0.24103059, 0.10142431],
       [0.19300178, 0.43500937, 0.84595681]])

## Viewing Arrays and matrices

In [23]:
# to find Unique elements 
np.unique(random_array1)

array([0, 2, 4, 5, 6, 7, 8])

# Manipulating Arrays 

## arithmethic operations on numpy

In [24]:
a1

array([1, 2, 3])

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [27]:
a1 - ones 

array([[0., 1., 2.],
       [0., 1., 2.]])

In [28]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [29]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [30]:
a1 // ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [31]:
a1 ** 2

array([1, 4, 9])

In [32]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [33]:
np.square(a1)

array([1, 4, 9])

In [34]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [35]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [36]:
np.add(a1,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

# Aggregation
### it means performing same operations on number of things 

In [37]:
listy_list=[1,2,3]
listy_list
type(listy_list)

list

In [38]:
#python function
sum(listy_list)

6

In [39]:
#Numpy function
np.sum(listy_list)

6

## Use python's method (`sum()`) in python datatypes and use numpy's method (`np.sum()`) in numpy's array

In [40]:
# create random array
random_array=np.random.random(10000)
random_array.size

10000

In [41]:
random_array[:10]

array([0.06413835, 0.54204733, 0.77470912, 0.40066659, 0.33980779,
       0.22517844, 0.89048667, 0.70494462, 0.86962676, 0.10138971])

In [42]:
%timeit sum(random_array)   # for python ope
%timeit np.sum(random_array) # for numpy ope

571 μs ± 30.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.39 μs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [43]:
59100 / 7.72

7655.440414507772

In [44]:
a2

array([[1. , 2.1, 3. ],
       [4. , 5. , 6.4]])

In [45]:
np.mean(a2)

3.5833333333333335

In [46]:
np.min(a2)

1.0

In [47]:
np.max(a2)

6.4

In [48]:
np.std(a2)

1.7948228015291339

In [49]:
np.var(a2)

3.221388888888889

In [50]:
np.sqrt(np.var(a2))

1.7948228015291339

In [51]:
# Demo of std,var
high_var_array=np.array([1,100,200,300,4000,5000])
low_var_array=np.array([2,4,6,8,10,12])

In [52]:
np.var(high_var_array),np.var(low_var_array)

(4296133.472222221, 11.666666666666666)

In [53]:
np.mean(high_var_array),np.mean(low_var_array)

(1600.1666666666667, 7.0)

In [54]:
np.std(high_var_array),np.std(low_var_array)

(2072.711623024829, 3.415650255319866)

# Reshape and transpose

In [55]:
a2

array([[1. , 2.1, 3. ],
       [4. , 5. , 6.4]])

In [56]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [60]:
a2_reshape=a2.reshape(2,3,1)
a2

array([[1. , 2.1, 3. ],
       [4. , 5. , 6.4]])

In [63]:
a3.reshape(3,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [66]:
# Transpose array = switch positions 
a2.T

array([[1. , 4. ],
       [2.1, 5. ],
       [3. , 6.4]])

# Dot product vs element wise

In [73]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [74]:
# ELement wise multiplication
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [75]:
# Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [76]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [78]:
mat1.T.shape

(3, 5)

In [79]:
np.dot(mat1.T,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

# Exercise : Nut Butter Store Sales

In [82]:
np.random.seed(0)
sale_amount=np.random.randint(20,size=(5,3))
sale_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [87]:
# Create dataframe
weekly_sales = pd.DataFrame(sale_amount,index=["Mon","Tues","Wed","Thu","Fri"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thu               4              6             12
Fri               1              6              7

In [88]:
# create price array
price=np.array([10,8,12])
price

array([10,  8, 12])

In [91]:

prices=pd.DataFrame(price.reshape(1,3),index=["Price"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [105]:
prices.shape,weekly_sales.shape

((1, 3), (5, 4))

In [107]:
weekly_sales.T

Mon  Tues   Wed   Thu  Fri
Almond Butter  12.0   3.0   9.0   4.0  1.0
Peanut Butter  15.0   3.0  19.0   6.0  6.0
Cashew Butter   0.0   7.0  18.0  12.0  7.0
Total ($)       NaN   NaN   NaN   NaN  NaN

# Comparison Arrays

In [108]:
a1

array([1, 2, 3])

In [109]:
a2

array([[1. , 2.1, 3. ],
       [4. , 5. , 6.4]])

In [110]:
a1>  a2

array([[False, False, False],
       [False, False, False]])

In [111]:
a1 <6

array([ True,  True,  True])

In [112]:
a1 >=a2

array([[ True, False,  True],
       [False, False, False]])

In [113]:
a1<a2

array([[False,  True, False],
       [ True,  True,  True]])

# Sorting arrays

In [115]:
random_array1

array([[8, 2, 0, 4, 4],
       [4, 7, 6, 8, 8],
       [4, 0, 5, 5, 4]])

In [116]:
np.sort(random_array1)

array([[0, 2, 4, 4, 8],
       [4, 6, 7, 8, 8],
       [0, 4, 4, 5, 5]])

In [117]:
# Check by their index
np.argsort(random_array1)

array([[2, 1, 3, 4, 0],
       [0, 2, 1, 3, 4],
       [1, 0, 4, 2, 3]], dtype=int64)

In [118]:
np.argmin(random_array1,axis=0)

array([1, 2, 0, 0, 0], dtype=int64)

In [119]:
np.argmax(random_array1,axis=1)

array([0, 3, 2], dtype=int64)

In [120]:
np.max(random_array1,axis=1)

array([8, 8, 5])

# Turn images into numpy arrays