In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape,arr1.ndim,arr1.dtype,arr1.size,type(arr1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
arr2.shape,arr2.ndim,arr2.dtype,arr2.size,type(arr2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
arr3.shape,arr3.ndim,arr3.dtype,arr3.size,type(arr3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
dataframe=pd.DataFrame(arr2)
dataframe

0  1  2
0  1  2  3
1  4  5  6

In [12]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
range=np.arange(0,100,3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[6, 4],
       [9, 5],
       [9, 3],
       [5, 0],
       [4, 0],
       [6, 6],
       [8, 6]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2=np.random.random((3,5))
random_array2

array([[0.64849933, 0.94854213, 0.86953463, 0.73358262, 0.65294768],
       [0.67443553, 0.87445092, 0.62750088, 0.67617745, 0.74095935],
       [0.34878525, 0.78979881, 0.49082955, 0.06340331, 0.5595891 ]])

In [24]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3=np.random.randint(0,10,size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array=np.random.randint(1,10,size=(3,7))
array
# Find the unique numbers in the array you just created
unique_number=np.unique(array)
unique_number

array([1, 2, 3, 5, 6, 7, 8, 9])

In [28]:
# Find the 0'th index of the latest array you created
array[0]

array([2, 5, 8, 9, 9, 1, 9])

In [30]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [34]:
Get the first 2 values of the first 2 rows of the latest array
arr=array[:2, :2]
arr

SyntaxError: invalid syntax (1962564676.py, line 1)

In [35]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5=np.random.randint(0,10,size=(3,5))
random_array5

array([[6, 8, 9, 9, 2],
       [6, 0, 3, 3, 4],
       [6, 6, 3, 6, 2]])

In [36]:
ones_array=np.ones((3,5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# Add the two arrays together
random_array5 + ones_array

array([[ 7.,  9., 10., 10.,  3.],
       [ 7.,  1.,  4.,  4.,  5.],
       [ 7.,  7.,  4.,  7.,  3.]])

In [38]:
# Create another array of ones of shape (5, 3)
ones_array2=np.ones((5,3))
ones_array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Try add the array of ones and the other most recent array together
ones_array + ones_array2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [40]:
# Create another array of ones of shape (3, 5)
ones_array3=np.ones((3,5))
ones_array3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# Subtract the new array of ones from the other most recent array
random_array5 - ones_array3

array([[ 5.,  7.,  8.,  8.,  1.],
       [ 5., -1.,  2.,  2.,  3.],
       [ 5.,  5.,  2.,  5.,  1.]])

In [45]:
# Multiply the ones array with the latest array
random_array5 * ones_array3

array([[6., 8., 9., 9., 2.],
       [6., 0., 3., 3., 4.],
       [6., 6., 3., 6., 2.]])

In [47]:
# Take the latest array to the power of 2 using '**'
random_array5 ** 2

array([[36, 64, 81, 81,  4],
       [36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4]])

In [48]:
# Do the same thing with np.square()
np.square(random_array5)

array([[36, 64, 81, 81,  4],
       [36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4]])

In [50]:
# Find the mean of the latest array using np.mean()
mean=np.mean(random_array5)
mean

4.866666666666666

In [51]:
# Find the maximum of the latest array using np.max()
maximum=np.max(random_array5)
maximum

9

In [52]:
# Find the minimum of the latest array using np.min()
minimum=np.min(random_array5)
minimum

0

In [53]:
# Find the standard deviation of the latest array
stan_devi=np.std(random_array5)
stan_devi

2.604269997949948

In [54]:
# Find the variance of the latest array
var=np.var(random_array5)
var

6.782222222222223

In [56]:
# Reshape the latest array to (3, 5, 1)
reshape=random_array5.reshape(3,5,1)
reshape

array([[[6],
        [8],
        [9],
        [9],
        [2]],

       [[6],
        [0],
        [3],
        [3],
        [4]],

       [[6],
        [6],
        [3],
        [6],
        [2]]])

In [57]:
# Transpose the latest array
random_array5.T

array([[6, 6, 6],
       [8, 0, 6],
       [9, 3, 3],
       [9, 3, 6],
       [2, 4, 2]])

In [59]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1=np.random.randint(0,10,size=(3,3))
a2=np.random.randint(0,10,size=(3,2))
a1,a2

(array([[3, 8, 2],
        [6, 5, 7],
        [8, 4, 0]]),
 array([[2, 9],
        [7, 5],
        [7, 8]]))

In [60]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[ 76,  83],
       [ 96, 135],
       [ 44,  92]])

In [61]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3=np.random.randint(0,10,size=(4,3))
a4=np.random.randint(0,10,size=(4,3))

In [62]:
a3,a4

(array([[3, 0, 0],
        [9, 3, 6],
        [1, 2, 0],
        [4, 0, 7]]),
 array([[0, 0, 1],
        [1, 5, 6],
        [4, 0, 0],
        [2, 1, 4]]))

In [63]:
# Perform a dot product on the two newest arrays you created
np.dot(a3,a4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [64]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a3.T,a4)

array([[21, 49, 73],
       [11, 15, 18],
       [20, 37, 64]])

In [65]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a4=np.random.randint(0,10,size=(3,2))
a5=np.random.randint(0,10,size=(3,2))

In [66]:
a4,a5

(array([[9, 5],
        [6, 3],
        [6, 7]]),
 array([[0, 5],
        [7, 4],
        [3, 1]]))

In [67]:
# Compare the two arrays with '>'
a4>a5

array([[ True, False],
       [False, False],
       [ True,  True]])

In [68]:
# Compare the two arrays with '>='
a4>=a5

array([[ True,  True],
       [False, False],
       [ True,  True]])

In [69]:
# Find which elements of the first array are greater than 7
a4 >7

array([[ True, False],
       [False, False],
       [False, False]])

In [70]:
# Which parts of each array are equal? (try using '==')
a4 == a5

array([[False,  True],
       [False, False],
       [False, False]])

In [71]:
# Sort one of the arrays you just created in ascending order
np.sort(a5)

array([[0, 5],
       [4, 7],
       [1, 3]])

In [72]:
# Sort the indexes of one of the arrays you just created
np.argsort(a5)

array([[0, 1],
       [1, 0],
       [1, 0]], dtype=int64)

In [73]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a5)

2

In [75]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a5)

0

In [76]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a5,axis=1)

array([1, 0, 0], dtype=int64)

In [77]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a5,axis=0)

array([0, 2], dtype=int64)

In [78]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 0.58685709,  2.19045563, -0.99053633, -0.56629773,  0.09965137],
       [-0.50347565, -1.55066343,  0.06856297, -1.06230371,  0.47359243],
       [-0.91942423,  1.54993441, -0.78325329, -0.32206152,  0.81351722]])

In [79]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])